version: '3.8'
name: 'ts-monolith-cashflow'

services:
  cashflow:
    container_name: cashflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    networks:
      - ts-monolith-cashflow

networks:
  ts-monolith-cashflow:
    name: ts-monolith-cashflow
    driver: bridge