version: '3.8'
name: 'ts-monolith-cashflow'

services:
  cashflow:
    container_name: cashflow
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    networks:
      - ts-monolith-cashflow

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - ts-monolith-cashflow
    env_file:
      - .env
    volumes:
      - ./infra/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  ts-monolith-cashflow:
    name: ts-monolith-cashflow
    driver: bridge